server:
  port: 9090
  tomcat:
    min-spare-threads: 50
    max-threads: 1000
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/demo?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: postgres
    password: 1234
    hikari:
      maximum-pool-size: 30
      minimum-idle: 30
  jpa:
    show-sql: true
    properties:
      hibernate:
        temp.use_jdbc_metadata_defaults: false

property:
    jwt:
      token:
        expire-length: 2600000


